import assert from "node:assert/strict";
import { access, readFile } from "node:fs/promises";
import test from "node:test";

test("static Netlify export contains the secure app shell and assets", async () => {
  const html = await readFile(new URL("../out/index.html", import.meta.url), "utf8");
  const source = await readFile(new URL("../app/page.tsx", import.meta.url), "utf8");
  assert.match(html, /AI Face Monitor/);
  assert.match(html, /Preparing your dashboard/);
  assert.match(html, /Connecting recognition, attendance and secure records/);
  assert.match(html, /AI Face Monitor logo/);
  assert.doesNotMatch(html, /Starter Project|Codex is working/);
  assert.match(source, /AI server is not responding/);
  assert.match(source, /Try Again/);
  assert.match(source, /controller\.abort\(\)/);
  assert.match(source, /Search name, roll or department/);
  assert.match(source, /face-monitor-preferences/);
  assert.match(source, /form\.append\("threshold"/);
  assert.match(source, /AI reconnecting/);
  assert.match(source, /Show password/);
  assert.doesNotMatch(source, /Class Sessions|All departments/);
  assert.match(source, /Recognition record corrected/);
  assert.match(source, /custom-reports/);
  assert.match(source, /Download Backup/);
  assert.match(source, /Audit Activity/);
  assert.match(source, /Manual Attendance/);
  assert.match(source, /Forgot password\?/);
  assert.match(source, /Teacher \/ Admin Accounts/);
  assert.match(source, /auth\/password\/change/);
  assert.match(source, /Advanced live check/);
  assert.match(source, /Import CSV/);
  assert.match(source, /Attendance Percentage/);
  assert.match(source, /Captured Image Retention/);
  assert.match(source, /Backup & Restore/);
  assert.match(source, /Brevo Email Alerts/);
  assert.doesNotMatch(source, /Gmail Attendance Alerts/);
  assert.doesNotMatch(source, /WhatsApp/);
  assert.match(source, /Real-world Readiness/);
  await access(new URL("../out/favicon.svg", import.meta.url));
  await access(new URL("../out/logo.svg", import.meta.url));
  await access(new URL("../out/og.png", import.meta.url));
});
